In [1]:
import numpy as np

matrixA = np.array([[1, 2, 3, 4], [2, 3, 4, 1], [3, 4, 1, 2], [4, 1, 2, 3]])
matrixB = np.array([[5, 4, 3, 2], [4, 3, 2, 5], [3, 2, 5, 4], [2, 5, 4, 3]])
vektorB = np.array([1, 2, 3, 4])

# Teilaufgabe a
print(np.dot(matrixA, vektorB))
print(np.dot(matrixB, vektorB))
print(matrixA.T)
print(matrixB.T)
print(np.dot(matrixA.T, matrixA))
print(np.dot(matrixB.T, matrixB))


Teilaufgabe a
[30 24 22 24]
[30 36 38 36]
[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]
 [4 1 2 3]]
[[5 4 3 2]
 [4 3 2 5]
 [3 2 5 4]
 [2 5 4 3]]
[[30 24 22 24]
 [24 30 24 22]
 [22 24 30 24]
 [24 22 24 30]]
[[54 48 46 48]
 [48 54 48 46]
 [46 48 54 48]
 [48 46 48 54]]


In [2]:
import numpy as np

matrixA = np.array([[1, 2, 3, 4], [2, 3, 4, 1], [3, 4, 1, 2], [4, 1, 2, 3]])
matrixB = np.array([[5, 4, 3, 2], [4, 3, 2, 5], [3, 2, 5, 4], [2, 5, 4, 3]])
vektorB = np.array([1, 2, 3, 4])

# Teilaufgabe b
print(np.dot(matrixA[3,:], matrixB[:,1]))

38


In [2]:
import numpy as np

matrixA = np.array([[1, 2, 3, 4], [2, 3, 4, 1], [3, 4, 1, 2], [4, 1, 2, 3]])
matrixB = np.array([[5, 4, 3, 2], [4, 3, 2, 5], [3, 2, 5, 4], [2, 5, 4, 3]])
vektorB = np.array([1, 2, 3, 4])

# Teilaufgabe c
print(np.sum(matrixB, axis=1))
print(np.sum(matrixA, axis=0))

[14 14 14 14]
[10 10 10 10]
